name: Build Funkin.NET

# Controls when the action will run. 
#on:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Runs a set of commands using the runners shell
      - name: Build script
        if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'Safe to Test')
        shell: bash
        run: |
          dotnet build Funkin.NET.sln "Debug|AnyCPU"
          dotnet build Funkin.NET.sln "Release|AnyCPU"
          
      - name: Upload Debug Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows Debug Build
          path: |
            ./Funkin.NET.Desktop/bin/Debug/
            
      - name: Upload Release Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows Release Build
          path: |
            ./Funkin.NET.Desktop/bin/Release/